name: "Elixir pre steps"
description: "Runs elixir pre steps"

inputs:

  otp_version_spec: 
    description: "OTP version"
    required: true
  elixir_version_spec: 
    description: "Elixir version"
    required: true
  mix_env: 
    description: "Mix env profile (test/dev)"
    required: true
  deps_cache_prefix: 
    description: "Dependency cache prefix"
    required: true
  build_cache_prefix: 
    description: "Build cache prefix"
    required: true

runs:
  using: "composite"
  steps:      
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1.9
        id: setup
        with:
          otp-version: ${{ env.OTP_VERSION_SPEC }}
          elixir-version: ${{ env.ELIXIR_VERSION_SPEC }}
      - name: Cache Keys
        id: keys
        shell: bash
        run: |
          echo ::set-output name=deps_key::deps-${{ runner.os }}
          echo ::set-output name=lockfile_key::${{ hashFiles('mix.lock') }}
          echo ::set-output name=build_key::build-${{ runner.os }}-${{ env.MIX_ENV }}
          echo ::set-output name=version_key::${{ steps.setup.outputs['otp-version'] }}-${{ steps.setup.outputs['elixir-version'] }}
          echo ::set-output name=files_key::${{ hashFiles('apps/*/lib/**/*.ex','apps/*/test/**/*.ex','mix.lock') }}
          echo ::set-output name=deps_cache_prefix::${{ env.DEPS_CACHE_PREFIX }}
          echo ::set-output name=build_cache_prefix::${{ env.BUILD_CACHE_PREFIX }}
      - uses: actions/cache@v2.1.6
        id: deps_cache
        with:
          path: deps
          key: ${{ steps.keys.outputs.deps_cache_prefix }}${{ steps.keys.outputs.deps_key }}-${{ steps.keys.outputs.lockfile_key }}
          restore-keys: |
            ${{ steps.keys.outputs.deps_cache_prefix }}${{ steps.keys.outputs.deps_key }}-
      - uses: actions/cache@v2.1.6
        id: build_cache
        with:
          path: _build
          key: ${{ steps.keys.outputs.build_cache_prefix }}${{ steps.keys.outputs.build_key }}-${{ steps.keys.outputs.version_key }}-${{ steps.keys.outputs.files_key }}
          restore-keys: |
            ${{ steps.keys.outputs.build_cache_prefix }}${{ steps.keys.outputs.build_key }}-${{ steps.keys.outputs.version_key }}-
      - name: Authorize Hex Organization
        shell: bash
        run: mix hex.organization auth peek --key ${{ secrets.PEEK_HEX_KEY }}
      - name: Authorize Oban
        shell: bash
        run: mix hex.organization auth oban --key ${{ secrets.OBAN_KEY }}
      - name: Install dependencies
        if: steps.deps_cache.outputs['cache-hit'] != 'true'
        shell: bash
        run: mix deps.get
      - name: Compile
        if: steps.build_cache.outputs['cache-hit'] != 'true'
        shell: bash
        run: mix compile --warnings-as-errors
